version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_karenmora
    restart: always
    environment:
      POSTGRES_DB: karenmora
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123  # Sin contraseña, según tu DATABASE_URL
    ports:
      - "6666:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
